# Generated by Django 5.0 on 2023-12-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_comment_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
    ]
